version: '3.8'

services:
  model:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .logs:/app/logs
    command: >
      gunicorn -w 4 -b 0.0.0.0:8000 app:app
      --access-logfile logs/access.log
      --error-logfile logs/error.log